### ISSUE TITLE
Do not show functions after last VSC update.

### ISSUE THREAD

**Issue by jcstorino** [qrti/funcList#10]
(by translator)
I'm not sure which VSC update, but the extension stopped working properly.

Follow my extension config and a sample file ( rename to .prw ).

Thank You.

    **_"funcList": {
        "doubleSpacing": false,
        "filters": [
            {
                "extensions": [
                    ".PRW",
                    ".prw",
                    ".PRX",
                    ".prx",
                    ".PRG",
                    ".prg"
                ],
                "native" : "/\\b(method [a-z0-9() ,]+ cla|wsservice [a-z0-9].*|wsmethod [a-z0-9]+.*ws.*|static function .*|user function .*|wsstruct .*)+/ig",
                "display": "/\\b(method|wsservice|wsmethod|static function|user function|wsstruct)+\\s{1}[a-z0-9_]+/0i",
                "sort": 0
            }
        ]
    },_**

[RGENM110.txt](https://github.com/qrti/funcList/files/2866554/RGENM110.txt)

**Comment by hsmyers** [comment]
Let me pile-on here…I'm using latest 1.32.0-insider and all it shows is a blank window :( Filter in question is:

          "extensions": [
            ".coffee"
          ],
          "native": "/[^\\-]+\\-\\>$/",
          "display": "/(^\\w+)/1",
          "sort": 1
        },
Looking forwar to a patch, will try to be patient :)

**Comment by qrti** [comment]
I'm on it ...

**Comment by qrti** [comment]
hope it is done ;) ...
used virtual documents are strictly read only now, so lists stayed suddenly empty
