### ISSUE TITLE
Will funclist support golang

### ISSUE THREAD

**Issue by EasonZhao** [qrti/funcList#11]
there is my config:
"funcList": {
        "doubleSpacing": false,
        "filters": [
            {
                "extensions": [
                    ".go",
                    ".h"
                ],
                "native": "/^[a-z]+\\s+(\\(([a-z]+)\\s\\*([a-z]+)\\)\\s)?\\w+\\(/mgi",
                "display": "/.*/",
                "sort": 0
            }
        ]
    }
display methods is well,but goto method not work if it's a func of struct.

**Comment by qrti** [comment]
maybe you can refine your regEx, but not all problems are solvable with it

for easy testing you can use an online regEx engine, for example [regex101.com](https://regex101.com/)
(you have to omit regEx group syntax for testing)
