### ISSUE TITLE
[HELP] Keyboard shortcut example

### ISSUE THREAD

**Issue by gcobb321** [qrti/funcList#16]
I'm new to VSCode and would like your help. I'm trying to set up a keyboard shortcut for funcList for Python. The Python part works great but I'm lost as to how to set up the keyboard shortcut mapping in VSCode that will do the same thing as F1>Show Functions. I'd like your help. An example would be great.

Thanks.

I have tried., without success:
 {
        "key": "ctrl" "a",
        "command": "extensions.action.showFunction",
        "when": "editorTextFocus"
    }

It doesn't like the "key" or the "command". The "key" I can probably figure out but do not have a clue as to what the "command" should be.

**Comment by deanhouseholder** [comment]
I got it to work with this keybinding config:
```
    {
        "key": "ctrl+f12",
        "command": "editor.printFunctions",
        "when": "editorTextFocus",
    },
```
