### ISSUE TITLE
Insert newlines between functions in list

### ISSUE THREAD

**Issue by ArturoDent** [qrti/funcList#2]
I really like this extension.  I have modified the settings to produce this type of list:

```
clearSearchInput()
getQuery(event)
getSearchSpecialsQuery(evt)
escapeRegExp(string)
searchTree(query2)
```
I would like to be able to insert a newline between each entry to make the list easier to read.  The settings I am using:

// so that "function someName(arg1, arg2) is captured
 ` "funcList.nativeFilter": "/^[a-z]+\\s+\\w+\\s*\\(.*\\)/mgi",
`
  // now display  "someName(arg1, arg2)"
 ` "funcList.displayFilter": "/\\S* +(\\w+\\s*\\(.*\\))/1"`

**Comment by qrti** [comment]
added new option 'doubleSpacing' in settings

**Comment by ArturoDent** [comment]
Thank you.
