### ISSUE TITLE
Filtering not working for PowerShell functions

### ISSUE THREAD

**Issue by Paradox355** [qrti/funcList#3]
Cannot get filtering working for PowerShell functions. I have thoroughly tested the regex statements which work everywhere except within this extension. Here are the settings I am using:

`"funcList.nativeFilter": "/function\\s+\\w+-?\\w*\\s*{/img"`
`"funcList.displayFilter": "/(?![function])(?!\\s+)\\w+-?\\w*/img"`

Search string example:

```
Function Verb-Noun {
     #Some filler here
}
```

**Comment by Paradox355** [comment]
Found the proper filtering. It was the display filter that was off; looks like it only works using capture groups and not by using negative lookaheads. Here's the working display filter:

`"funcList.displayFilter": "/function\\s+(\\w+-?\\w*)/1i"`

Might be worthwhile to add this to examples; it was not easy to figure out due to lack of documentation regarding VS Code RegEx convention.

![image](https://user-images.githubusercontent.com/18059847/32058890-869822b0-ba38-11e7-96c9-f9e3b1b04e9e.png)


FYI. This was tested against the AppDeployToolkitMain.ps1 of the [PSAppDeployToolkit](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit)

Thanks.

**Comment by qrti** [comment]
I will add it to examples, thank your very much!
