### ISSUE TITLE
clicking an entry will not redirect the user

### ISSUE THREAD

**Issue by ArsBinarii** [qrti/funcList#4]
OSX 10.13.1
VS code 1.18.1
Version: 

7.1.0

    "funcList.nativeFilter": "/^[a-z]+\\s+\\w+\\(/mgi"

**Comment by PJkeeh** [comment]
Same here:
```
"funcList.nativeFilter": "/TOOP Method.+/g",
"funcList.displayFilter": "/TOOP Method (.+)\\{.+/1",
```
The functions show up correctly, but clicking them don't do anything. Clicking the "Switch sort" option also does not switch the sort option.

**Comment by pip182** [comment]
Works great on my windows machine but not on my Linux one. 

I guess I should mention how much I love this extension, it's exactly what vscode was missing for me. I know I can use the symbol browser but I like having a list of all my functions that I can toggle between with the click of a mouse. So other than redirecting not working I say good job!

**Comment by qrti** [comment]
The latest version V7.2.1 should work with Linux now. 
For MacOS I lack the possibility to make tests.
