### ISSUE TITLE
feature request: languadge depended regexps

### ISSUE THREAD

**Issue by hibernick** [qrti/funcList#5]
Hi,
Thanks for the work!

I would like to suggest a feature to make possible to opt a regexp depending on the file language is edited.

E.g. to add an option of map [lang: regexp, lang2: regexp2] and if the file type matches on of the file type it uses a particular regexp otherwise It continues to use the global one.

Thanks a lot in advance,
Mik

**Comment by qrti** [comment]
No bad thought, I will consider it.

So far I have fitting regexps in the local settings.json of my project folders, but it is for example hard to find a well working single regexp for both .c and .cpp files ...

**Comment by qrti** [comment]
Done.
