### ISSUE TITLE
No Filter fo Filetype

### ISSUE THREAD

**Issue by mahomedh** [qrti/funcList#6]
Hi

Thanks for this great extension. Unfortunately the latest update has broken this extension for me as I now get the error "no filter for filetype". I have tried checking the config for "filters.extensions" to try and update it with my extension (*.mq4) but it says this is an unknown configuration setting. I have also tried uninstalling and reinstalling but it hasn't helped. Any advice on how to make this work again please?

**Comment by qrti** [comment]
go to global (default) settings with 
'Menu/File/Preferences/Settings'
enter funcList in the search field
right click the little pen left to its first entry and do a 'Copy to Settings'
add your entry to 'User Settings'

or make a copy of funcList settings in local .vscode folders

check for correct bracing and commas
an entry should looks like this, maybe the 'asterisk' in '.mq4 'is the culprit?


```
"funcList": {
       
        ...

        "extensions": [
          ".mq4"
        ],
        "native": "your native filter",
        "display": "your display filter",
        "sort": 0
      },

      ...

}
```

**Comment by mahomedh** [comment]
Thank you. I was searching for "functions" and "filters" and "filters.extensions". I can see the documentation has now been updated and it is definitely much clearer. I've also created my own filter based on the .c native filter and the .cpp display and it works great!

`

         {
            "extensions": [
               ".mq4"
            ],
            "native": "/(?:^\\w+\\s+|^)\\w+[:]*\\w+\\(/mgi",
            "display": "/\\S* +(\\w+)/1",
            "sort": 0
         }

`

>
