### ISSUE TITLE
Multiple keyword 

### ISSUE THREAD

**Issue by ecus** [qrti/funcList#8]
Please i want to add **.4gl** files, but it use 
```
FUNCTION name()
END FUNCTION
```
```
REPORT  name()
END
```

```
MAIN
END MAIN
```
How can i do work with that keywords??.

Actually just work for `FUNCTION`

thanks

**Comment by qrti** [comment]
if you study the examples you should be able to manage inventing a fitting regex, very helpful for try and error is this page

[https://regex101.com/](url)
